require("core.plugins-config.gruvbox")
require("core.plugins-config.lualine")
require("core.plugins-config.nvim-tree")
require("core.plugins-config.treesitter")
require("core.plugins-config.telescope")
require("core.plugins-config.lsp-config")
require("core.plugins-config.autopair")
require("core.plugins-config.gitsigns")
require("core.plugins-config.comment")
-- require("core.plugins-config.null-ls")
